### ISSUE TITLE
Need some help for developing this component

### ISSUE THREAD

**Issue by WinfredH** [mariomka/vue-datetime#150]
## Versions
- vue: -
- vue-datetime: 1.0.0-beta.10
- luxon: -
- node: 10.13
- system: ubuntu

### Description:

vue-datetime helps me a lot. However, my boss wanna more customized feature in a datetime component. So I want to do some development baseed on your work.

When I run "npm install", I got some errors what I have not met.

`
Error: Unknown transform 'collections'
    at error (/home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:170:12)
    at /home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:8937:6
  plugin: 'vue',
  id: '/home/mine/Development/vue-datetime/src/Datetime.vue' }
{ Error: Unknown transform 'collections'
    at error (/home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:170:12)
    at /home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:8937:6
  plugin: 'vue',
  id: '/home/mine/Development/vue-datetime/src/Datetime.vue' }
{ Error: Unknown transform 'collections'
    at error (/home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:170:12)
    at /home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:8937:6
  plugin: 'vue',
  id: '/home/mine/Development/vue-datetime/src/Datetime.vue' }
{ Error: Unknown transform 'collections'
    at error (/home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:170:12)
    at /home/mine/Development/vue-datetime/node_modules/rollup/dist/rollup.js:8937:6
  plugin: 'vue',
  id: '/home/mine/Development/vue-datetime/src/Datetime.vue' }

> vue-xz-datetime@0.5.0 demo:build /home/mine/Development/vue-datetime
> webpack --config build/webpack.config.demo.js

Node#before is deprecated. Use Node#raws.before
Hash: 30f0fc82318ece0752bf
Version: webpack 2.7.0
Time: 4968ms
 Asset    Size  Chunks                    Chunk Names
app.js  609 kB       0  [emitted]  [big]  main
   [0] (webpack)/buildin/global.js 509 bytes {0} [built]
   [1] ./~/luxon/build/cjs-browser/luxon.js 230 kB {0} [built]
   [2] ./demo/src/app.css 1.17 kB {0} [built]
   [3] ./~/vue/dist/vue.js 341 kB {0} [built]
   [4] ./demo/src/app.js 953 bytes {0} [built]
   [5] ./~/css-loader!./~/postcss-loader/lib?{}!./demo/src/app.css 2.38 kB {0} [built]
   [6] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
   [7] ./~/process/browser.js 5.42 kB {0} [built]
   [8] ./~/setimmediate/setImmediate.js 6.47 kB {0} [built]
   [9] ./~/style-loader/addStyles.js 9.15 kB {0} [built]
  [10] ./~/style-loader/fixUrls.js 3.01 kB {0} [built]
  [11] ./~/timers-browserify/main.js 2.02 kB {0} [built]

ERROR in ./demo/src/app.js
Module not found: Error: Can't resolve '../../dist/vue-datetime' in '/home/mine/Development/vue-datetime/demo/src'
 @ ./demo/src/app.js 9:19-53

ERROR in ./demo/src/app.js
Module not found: Error: Can't resolve '../../dist/vue-datetime.css' in '/home/mine/Development/vue-datetime/demo/src'
 @ ./demo/src/app.js 13:0-38
`

how should I deal with the errors ? Or what should I prepare for development environment ?

**Comment by WinfredH** [comment]
ok, I have done by import .vue files from 'vue-datetime/src'

**Comment by soyjonathanespinosa** [comment]
@WinfredH Can you please help me? I have the same issue:

{ Error: Unknown transform 'collections'
    at error (\node_modules\rollup\dist\rollup.js:170:12)
    at \node_modules\rollup\dist\rollup.js:8937:6
  plugin: 'vue',
  id: '\\src\\Datetime.vue' }}

Thank you

**Comment by mariomka** [comment]
I get the same error trying to update dependencies, for the moment the solution is to install dependencies with yarn, it uses `yarn.lock` to install the same versions.

**Comment by arboehme** [comment]
There is some incompatibility issues between vue 2.x and rollup-plugin-vue 2.x versions. Update to the latest rollup-plugin-vue version should help

PS: created the corresponding pull request:
https://github.com/mariomka/vue-datetime/pull/211
