### ISSUE TITLE
Problem with zone prop in IE 11

### ISSUE THREAD

**Issue by kenazs** [mariomka/vue-datetime#44]
Hello everyone, there is a problem with zone property in IE 11, in Chrome works good. If zone is "America/New_York", for example, input is always "Invalid Date". If 'local', 'UTC+3' works fine. Any suggestions?

<datetime
            type="datetime"
            input-class="form-control"
            :value="value"
            :value-zone="valueZone"
            :zone="zone"
            @input="handleDateInput"
>
</datetime>

**Comment by mariomka** [comment]
I think it's related to Intl support, see moment/luxon#169

Can you try the polyfill?

**Comment by kenazs** [comment]
Yes, i tried polyfill, but without <script src="https://unpkg.com/date-time-format-timezone@latest/build/browserified/date-time-format-timezone-complete-min.js"></script> 
Now, as in the example (https://jsfiddle.net/q37jzjL2/) i get this error in console.

Uncaught TypeError: Method Intl.DateTimeFormat.prototype.formatToParts called on incompatible receiver #<b>
    at b.formatToParts (native)
    at partsOffset (https://moment.github.io/luxon/global-filled/luxon.js:2191:23)
    at IANAZone.offset (https://moment.github.io/luxon/global-filled/luxon.js:2260:37)
    at new DateTime (https://moment.github.io/luxon/global-filled/luxon.js:6705:60)
    at Function.local (https://moment.github.io/luxon/global-filled/luxon.js:6760:14)
    at window.onload (https://fiddle.jshell.net/q37jzjL2/show/:47:28)
